// <auto-generated />
using System;
using IndependentContracts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IndependentContracts.Migrations
{
    [DbContext(typeof(IndependentContractsContext))]
    [Migration("20200806212819_tableUpdates")]
    partial class tableUpdates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IndependentContracts.Models.Armory", b =>
                {
                    b.Property<int>("ArmoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("WeaponName");

                    b.HasKey("ArmoryId");

                    b.ToTable("Armories");
                });

            modelBuilder.Entity("IndependentContracts.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("OrganizationId");

                    b.Property<DateTime>("accountCreationDate");

                    b.HasKey("ClientId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("IndependentContracts.Models.ClientContractor", b =>
                {
                    b.Property<int>("ClientContractorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientId");

                    b.Property<int>("ContractorId");

                    b.HasKey("ClientContractorId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractorId");

                    b.ToTable("ClientContractor");
                });

            modelBuilder.Entity("IndependentContracts.Models.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("RegionOfOperation");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("IndependentContracts.Models.ContractorArmory", b =>
                {
                    b.Property<int>("ContractorArmoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArmoryId");

                    b.Property<int>("ContractorId");

                    b.HasKey("ContractorArmoryId");

                    b.HasIndex("ArmoryId");

                    b.HasIndex("ContractorId");

                    b.ToTable("ContractorArmory");
                });

            modelBuilder.Entity("IndependentContracts.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("IndependentContracts.Models.Client", b =>
                {
                    b.HasOne("IndependentContracts.Models.Organization", "Organization")
                        .WithMany("Clients")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("IndependentContracts.Models.ClientContractor", b =>
                {
                    b.HasOne("IndependentContracts.Models.Client", "Client")
                        .WithMany("Contractors")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IndependentContracts.Models.Contractor", "Contractor")
                        .WithMany("Clients")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IndependentContracts.Models.ContractorArmory", b =>
                {
                    b.HasOne("IndependentContracts.Models.Armory", "Armory")
                        .WithMany("Contractors")
                        .HasForeignKey("ArmoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IndependentContracts.Models.Contractor", "Contractor")
                        .WithMany("Armories")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
